@url=http://localhost:3000

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "walter@gmail.com",
    "contraseña": "walter1234"
}

###
@token = {{login.response.body.token}}