@url=http://localhost:3000

### Registro de usuario
POST {{url}}/usuarios
Content-Type: application/json

{
    "nombre": "walter",
    "email": "walter@gmail.com",
    "contraseña": "walter1234"
}

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "walter@gmail.com",
    "contraseña": "walter1234"
}

###
@token = {{login.response.body.token}}

### Consultar usuarios
GET {{url}}/usuarios
Authorization: Bearer {{token}}

### Consultar por un usuario por ID
GET {{url}}/usuarios/3
Authorization: Bearer {{token}}

### Crear usuario desde sesión admin
POST {{url}}/usuarios
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Carlos",
    "email": "carlos@gmail.com",
    "contraseña": "hola1234"
}

### Modificar usuario
PUT {{url}}/usuarios/3
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Carlos Modificado",
    "email": "carlosmod@example.com"
}

### Quitar usuario
DELETE {{url}}/usuarios/3
Authorization: Bearer {{token}}